{{- if and .Values.rbac.create .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "redis-operator.leaderElectionRoleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "redis-operator.leaderElectionRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "redis-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
