{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redis-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: /metrics
    port: https
    scheme: https
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "redis-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
{{- end }}
