---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - koncache.greedykomodo
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - koncache.greedykomodo
  resources:
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - koncache.greedykomodo
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
